### ISSUE TITLE
[BUG] Not able to signup using Github and Google

### ISSUE THREAD

**Issue by MuthoniMN** [synthAI-Labs/server-OpenEdu#27]
The Github and Google buttons don't work on the sign up page.
![ezgif com-video-to-gif-converter](https://github.com/AI-RES/server/assets/105012834/dd1b75a5-2dc5-4064-89f7-cde612fd5fa1)

Suggestions: 
- use NextAuth to add Authentication

**Comment by Himasnhu-AT** [comment]
Yes, right now their functionalities aren't made.
Even the login and signup button aren't working in demo build. They will be initialized for MVP.

**Comment by Himasnhu-AT** [comment]
@MuthoniMN for now, if you wish, you can integrate the Google OAuth using passport library, or the github signin option. ALL the api endpoint for this are present in `auth.controller.ts`

**Comment by Himasnhu-AT** [comment]
You can issue at #30 #31

**Comment by MuthoniMN** [comment]
Okay. Let me check them out.

> You can issue at #30 #31
