### ISSUE TITLE
Implement JWT

### ISSUE THREAD

**Issue by Himasnhu-AT** [synthAI-Labs/server-OpenEdu#42]
Implement jwt auth token and store it using cookie

**Comment by AdeosunDeji** [comment]
I worked on this but i can't signup. StatusCode 500

**Comment by Himasnhu-AT** [comment]
Have you run the docker compose?

And while signing UP, did you web webclient locally or using deployed one?

**Comment by AdeosunDeji** [comment]
Yes i have and i'm running it locally

**Comment by Himasnhu-AT** [comment]
Okay, Kay I know the error you are getting

**Comment by rajeshj11** [comment]
@Himasnhu-AT 
Can I work on this? if no one is working on it
